stages:
  - Build
  - Test
  - Deploy

default:
  image: docker
  services:
    - name: 'docker:dind'
  before_script:
    - docker info

variables:
  DOCKER_TLS_CERTDIR: '/certs'
  SECURE_FILES_DOWNLOAD_PATH: './.secrets/'

Build:
  stage: Build
  before_script:
    - cd ./Go/
  script:
    - docker compose build

Test:
  stage: Test
  before_script:
    - cd ./Go/
    - apk add --no-cache curl bash
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash > /dev/null 2>&1
  script:
    - docker compose up globeboard-test --exit-code-from globeboard-test
    - docker compose cp globeboard-test:/root/report.xml ./report.xml
  after_script:
    - cd ./Go/
    - docker compose down globeboard-test
  coverage: '/coverage:\s+(\d+\.\d+)%\s+of statements/'
  artifacts:
    when: always
    paths:
      - ./Go/report.xml
    reports:
      junit: ./Go/report.xml

Deploy:
  stage: Deploy
  before_script:
    - cd ./Go/
    - docker compose down
    - apk add --no-cache curl bash
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash > /dev/null 2>&1
  script:
    - docker compose up globeboard -d
  after_script:
    - docker ps
  only:
    - main