stages:
  - Build
  - Test
  - Deploy

image: docker

services:
  - name: 'docker:dind'
    command: [ '--tls=false', '--host=tcp://0.0.0.0:2375' ]

variables:
  DOCKER_TLS_CERTDIR: ''
  SECURE_FILES_DOWNLOAD_PATH: './.secrets/'

Build:
  stage: Build
  before_script:
    - cd ./Go/
  script:
    - docker compose build

Test:
  stage: Test
  before_script:
    - cd ./Go/
    - apk add --no-cache curl bash go
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash > /dev/null 2>&1
  script:
    - docker compose up globeboard-test --exit-code-from globeboard-test
    - docker compose cp globeboard-test:/root/report.xml ./report.xml
  after_script:
    - cd ./Go/
    - docker compose down globeboard-test
  artifacts:
    when: always
    paths:
      - ./Go/report.xml
    reports:
      junit: ./Go/report.xml

Deploy:
  stage: Deploy
  before_script:
    - cd ./Go/
    - apk add --no-cache curl bash
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash > /dev/null 2>&1
  script:
    - docker compose up globeboard -d
  after_script:
    - cd ./Go/
    - docker compose down