version: '3.8'

services:
  globeboard:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../.env
    volumes:
      - ../db/firebaseCredentials.json:/root/firebaseCredentials.json
