services:
  globeboard:
    image: go-globeboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '0.0.0.0:${PORT}:${PORT}'
    restart: unless-stopped
    environment:
      PORT: ${PORT}
      FIREBASE_CREDENTIALS_FILE: /run/secrets/Firebase
      FIRESTORE_PROJECT_ID: ${FIRESTORE_PROJECT_ID}
    volumes:
      - ./web:/root/web:ro
    secrets:
      - Firebase

  globeboard-test:
    image: go-globeboard-test
    build:
      context: .
      dockerfile: Dockerfile-test
    restart: no
    environment:
      FIREBASE_CREDENTIALS_FILE: /run/secrets/Firebase
      FIRESTORE_PROJECT_ID: ${FIRESTORE_PROJECT_ID}
    volumes:
      - ./web:/root/web:ro
    secrets:
      - Firebase

secrets:
  Firebase:
    file: ${FIREBASE_CREDENTIALS_FILE}