# syntax=docker/dockerfile:1.2
FROM golang:1.22 AS builder

LABEL authors="Torgrim Thorsen"

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./

# Copy the source code.
COPY ../ ./

# Build
RUN CGO_ENABLED=0 GOOS=linux go test -c -installsuffix cgo -o main ./cmd/globeboard

# Use a minimal alpine image for the final build stage.
FROM alpine:3.19

# Install CA certificates.
RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the pre-built binary file from the previous stage.
COPY --from=builder /app/main .

# Run
CMD ["./main"]