# Use the official Golang image as a parent image
FROM golang:1.22

# Set the working directory inside the container
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./

# Download Go module dependencies
RUN go mod download

# Copy the rest of the service's source code
COPY ../ ./

# Specify the command to run tests
CMD ["go", "test", "./..."]
