version: '3.8'

services:
  globeboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - TOKEN=${TOKEN}
    volumes:
      - ./.secrets:/root/.secrets:ro
  globeboard-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - globeboard