version: '3.8'

services:
  globeboard:
    build: .
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASS=${AUTH_PASS}
      - TOKEN=${TOKEN}
    volumes:
      - ./.secrets:/credentials:ro
