version: "3.8"

services:
  globeboard-test:
    image: go-globeboard-test:latest
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - ./.secrets:/root/.secrets:ro
      - ./web:/root/web:ro
  globeboard:
    image: go-globeboard:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT=${PORT}
      - TOKEN=${TOKEN}
    volumes:
      - ./.secrets:/root/.secrets:ro
      - ./web:/root/web:ro
    depends_on:
      globeboard-test:
        condition: service_completed_successfully